name: Build CLO

on:
  push:
    branches: [ "CLO" ]
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Android kernel build
      uses: CharlesForson/Android-Kernel-Build-Action@master
      id: build
      env:
        NAME: CLO-BUILD
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: vendor/sm8150_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
